### ISSUE TITLE
Publishing path is wrong - custom template will not be loaded

### ISSUE THREAD

**Issue by stevenmackiol** [justijndepover/laravel-cookie-consent#3]
https://github.com/justijndepover/laravel-cookie-consent/blob/620d6137d58f03e5f2619af4e7c6ef411c70dc95/src/CookieConsentServiceProvider.php#L29

should be (The s after "cookie-consent" is not neccessary)

`__DIR__.'/../resources/views/cookiebar.blade.php' => base_path('resources/views/vendor/cookie-consent/cookiebar.blade.php'),`

**Comment by justijndepover** [comment]
Thanks, fixed
